services:

  db:
    restart: "no"
    ports:
      - 5435:5432

  iam:
    build:
      context: ./iam
    ports:
      - 8000:8000
    command:
      - fastapi
      - dev
      - --host=0.0.0.0
      - --port=8000
      - --reload
      - app/main.py
    volumes:
      - ./iam/app:/app/app
    develop:
      watch:
        - path: ./iam/pyproject.toml
          action: rebuild
