services:

  db:
    restart: "no"
    # ports:
    #   - "5432:5432"

  iam:
    build:
      context: ./iam
    ports:
      - "8000:8000"
    command:
      - fastapi
      - dev
      - --host=0.0.0.0
      - --port=8000
      - --reload
      - app/main.py
    develop:
      watch:
        - path: ./iam
          action: sync
          target: /app
          ignore:
            - ./iam/.venv
            - .venv
        - path: ./iam/pyproject.toml
          action: rebuild
