apiVersion: v1
kind: Secret
metadata:
  namespace: defi-portfolio-iam-ns
  name: defi-portfolio-iam-secrets
type: Opaque
stringData:
  username: your_db_user
  password: your_db_password
  database_url: postgresql://your_db_user:your_db_password@postgres:5432/mydatabase