apiVersion: v1
kind: Service
metadata:
  #namespace: defi-portfolio-iam-ns
  name: defi-portfolio-iam-service
spec:
  type: LoadBalancer
  selector:
    app: defi-portfolio-iam
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000